### ISSUE TITLE
Issue with tests/batcomputer.py | Problema com tests/batcomputer.py

### ISSUE THREAD

**Issue by vandaimer** [mateusoliveira43/cly#84]
**What is the issue? | Qual é o problema?**

While testing the examples (aka [tests/batcomputer.py](https://github.com/mateusoliveira43/cly/blob/main/tests/batcomputer.py)), I saw that the code isn't handling the input as `case-insentive`.

Also, I don't know if CLY?! should do it or not.

Anyway, if I type

- `tests/batcomputer.py id batman` it works fine.
- `tests/batcomputer.py id Batman` it throws an error.

Example:

```
(cly-py3.11) develop@docker:~/cly$ tests/batcomputer.py id batman
Bruce Wayne A.K.A. Batman 🦇
(cly-py3.11) develop@docker:~/cly$ 
(cly-py3.11) develop@docker:~/cly$ 
(cly-py3.11) develop@docker:~/cly$ tests/batcomputer.py id Batman
Traceback (most recent call last):
  File "/home/develop/cly/tests/batcomputer.py", line 5, in <module>
    CLI()
  File "/home/develop/cly/cly/config.py", line 382, in __call__
    self.commands[namespace.commands](
  File "/home/develop/cly/cly/config.py", line 66, in wrap
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/develop/cly/tests/batcomputer_cli/commands/identify.py", line 25, in identify
    responses = [
                ^
  File "/home/develop/cly/tests/batcomputer_cli/commands/identify.py", line 27, in <listcomp>
    get_oracle_data(alias) if oracle else get_alias_data(alias),
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/develop/cly/tests/batcomputer_cli/database.py", line 47, in get_alias_data
    return f"{CHARACTERS[alias]} A.K.A. {alias.title()} {ICONS[alias]}"
              ~~~~~~~~~~^^^^^^^
KeyError: 'Batman'
```

Also, I can see that if I type `tests/batcomputer.py id batmand` the result is `Batmand not identified by Batcomputer yet`, so the code handles very well the unknown values. So my first assumption might the wrong.

**What do you suggest? | O que sugere?**

- Decide if CLY?! should handle it, as adding a default option to make it `case-insensitive` (or not)
- Just fix the current example as it's not really related to the library - just showing how to use CLY?!

**Comment by mateusoliveira43** [comment]
Thanks for the issue @vandaimer 

The example should be `case-insensitive` (lacking tests)

I believe it is not a CLY related issue, just the example wrong implemented. [Here](https://github.com/mateusoliveira43/cly/blob/main/tests/batcomputer_cli/commands/identify.py#L30) we call with `lower` but then [here](https://github.com/mateusoliveira43/cly/blob/main/tests/batcomputer_cli/commands/identify.py#L27) it is called without `lower`. This would fix your related problem.

Do you want to work on this fix?

**Comment by vandaimer** [comment]
Sure! I can take it anytime!
